export const noteNames = [
  "A",
  "A#/Bb",
  "B",
  "C",
  "C#/Db",
  "D",
  "D#/Eb",
  "E",
  "F",
  "F#/Gb",
  "G",
  "G#/Ab",
];

export const enharmonics = {
  "C#": "Db",
  Db: "C#",
  "D#": "Eb",
  Eb: "D#",
  "F#": "Gb",
  Gb: "F#",
  "G#": "Ab",
  Ab: "G#",
  "A#": "Bb",
  Bb: "A#",
};

export const chordSpellings = {
  Cmaj: ["C", "E", "G"],
  Cmin: ["C", "D#/Eb", "G"],
  Caug: ["C", "E", "G#/Ab"],
  Cdim: ["C", "D#/Eb", "F#/Gb"],
  "C#/Dbmaj": ["C#/Db", "F", "G#/Ab"],
  "C#/Dbmin": ["C#/Db", "E", "G#/Ab"],
  "C#/Dbaug": ["C#/Db", "F", "A"],
  "C#/Dbdim": ["C#/Db", "E", "G"],
  Dmaj: ["D", "F#/Gb", "A"],
  Dmin: ["D", "F", "A"],
  Daug: ["D", "F#/Gb", "A#/Bb"],
  Ddim: ["D", "F", "G#/Ab"],
  "D#/Ebmaj": ["D#/Eb", "G", "A#/Bb"],
  "D#/Ebmin": ["D#/Eb", "F#/Gb", "A#/Bb"],
  "D#/Ebaug": ["D#/Eb", "G", "B"],
  "D#/Ebdim": ["D#/Eb", "F#/Gb", "A"],
  Emaj: ["E", "G#/Ab", "B"],
  Emin: ["E", "G", "B"],
  Eaug: ["E", "G#/Ab", "C"],
  Edim: ["E", "G", "A#/Bb"],
  Fmaj: ["F", "A", "C"],
  Fmin: ["F", "G#/Ab", "C"],
  Faug: ["F", "A", "C#/Db"],
  Fdim: ["F", "G#/Ab", "B"],
  "F#/Gbmaj": ["F#/Gb", "A#/Bb", "C#/Db"],
  "F#/Gbmin": ["F#/Gb", "A", "C#/Db"],
  "F#/Gbaug": ["F#/Gb", "A#/Bb", "D"],
  "F#/Gbdim": ["F#/Gb", "A", "C"],
  Gmaj: ["G", "B", "D"],
  Gmin: ["G", "A#/Bb", "D"],
  Gaug: ["G", "B", "D#/Eb"],
  Gdim: ["G", "A#/Bb", "C#/Db"],
  "G#/Abmaj": ["G#/Ab", "C", "D#/Eb"],
  "G#/Abmin": ["G#/Ab", "B", "D#/Eb"],
  "G#/Abaug": ["G#/Ab", "C", "E"],
  "G#/Abdim": ["G#/Ab", "B", "D"],
  Amaj: ["A", "C#/Db", "E"],
  Amin: ["A", "C", "E"],
  Aaug: ["A", "C#/Db", "F"],
  Adim: ["A", "C", "D#/Eb"],
  "A#/Bbmaj": ["A#/Bb", "D", "F"],
  "A#/Bbmin": ["A#/Bb", "C#/Db", "F"],
  "A#/Bbaug": ["A#/Bb", "D", "F#/Gb"],
  "A#/Bbdim": ["A#/Bb", "C#/Db", "E"],
  Bmaj: ["B", "D#/Eb", "F#/Gb"],
  Bmin: ["B", "D", "F#/Gb"],
  Baug: ["B", "D#/Eb", "G"],
  Bdim: ["B", "D", "F"],
};

// for ensuring the 'root' note with default vallues (picking from '3/4' octave range) is lowest note in frequencies returned
export const absoluteNoteVals = {
  C: 0,
  "C#/Db": 1,
  D: 2,
  "D#": 3,
  E: 4,
  F: 5,
  "F#/Gb": 6,
  G: 7,
  "G#/Ab": 8,
  A: 9,
  "A#/Bb": 10,
  B: 11,
};
